
spring:
  profiles: cloud
  neo4j:
    host: ${SPRING_NEO4J_HOST:192.168.99.101}
    port: ${SPRING_NEO4J_PORT:7474}
---
spring:
  profiles: development
  neo4j:
    host: ${SPRING_NEO4J_HOST:192.168.99.101}
    port: ${SPRING_NEO4J_PORT:7474}
---
spring:
  profiles: docker
  neo4j:
    host: ${SPRING_NEO4J_HOST:neo4j}
    port: ${SPRING_NEO4J_PORT:7474}
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
---
spring:
  profiles: test
  neo4j:
    host: ${SPRING_NEO4J_HOST:192.168.99.101}
    port: ${SPRING_NEO4J_PORT:7474}
eureka:
  client:
    enabled: false
---
spring:
  profiles: dev
  neo4j:
    host: ${SPRING_NEO4J_HOST:neo4j}
    port: ${SPRING_NEO4J_PORT:7474}
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
---
spring:
  profiles: openshift
  neo4j:
    host: ${OPENSHIFT_NEO4J_DB_HOST}
    port: ${OPENSHIFT_NEO4J_DB_PORT}
eureka:
  instance:
    # prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service-uncrated-doper.cfapps.io/eureka/
